Set the AES Key to configurable
lucheng0127/virtuallan pull request #11
Opened 2024-06-26 03:59 UTC by w1543565388

2024-06-26 05:47 UTC, lucheng0127 commented on pkg/cli/client.go
> +				Required: false,
Required true

2024-06-26 05:49 UTC, lucheng0127 commented on pkg/client/client.go
> +	cipher.AESKEY = cCtx.String("key")
If use wrong key, or invalidate key, weather the client gonna login timeout

2024-06-26 05:51 UTC, lucheng0127 commented on pkg/server/server.go
> +	if ok := utils.ValidateKey(svc.Key); !ok {
Add a new line will be better

2024-06-26 05:52 UTC, lucheng0127 commented on pkg/utils/validate.go
> +func ValidateKey(key string) bool {
Why don't use it in aes.go NewAESCipher

2024-06-26 05:53 UTC, lucheng0127 requested changes
Key is required

2024-06-27 01:19 UTC, lucheng0127 commented on pkg/config/config.go
> +	Key       string `yaml:"key" validate:"required"`
Use validate.RegisterValidation  to validate key
Also other filed is required except web

2024-06-27 03:21 UTC, w1543565388 commented
It has been modified according to the format

2024-06-27 03:37 UTC, lucheng0127 reviewed
LGTM

2024-06-27 03:39 UTC, merged